<a href="https://colab.research.google.com/github/oluarolu/checkfolder/blob/master/GeneratingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.random()

0.6896786186289863

In [17]:
np.random.random((2, 3))

array([[0.60074797, 0.33888215, 0.53461963],
       [0.05188506, 0.32926889, 0.68321159]])

To get random number from Guassian distribution or normal distribution us randn

In [19]:
np.random.randn(2, 3)

array([[ 0.32622801,  0.23170652,  0.12450066],
       [-0.06191048, -1.92010004, -0.26395442]])

In [0]:
R = np.random.randn(10000)

In [21]:
R.mean()

-0.013251760042861065

In [22]:
np.mean(R)

-0.013251760042861065

In [23]:
R.var()

1.0068868033893486

In [24]:
R.std()

1.0034374935138455

In [0]:
R = np.random.randn(10000, 3)

In [27]:
R.mean(axis =0)

array([ 0.01547586,  0.00885677, -0.00942408])

In [30]:
R.mean(axis =1).shape

(10000,)

In [32]:
np.cov(R).shape

(10000, 10000)

In [33]:
np.cov(R.T)

array([[ 1.00126847, -0.01773938, -0.01651459],
       [-0.01773938,  1.0260629 ,  0.01182094],
       [-0.01651459,  0.01182094,  1.0043827 ]])

In [34]:
np.cov(R, rowvar = False)

array([[ 1.00126847, -0.01773938, -0.01651459],
       [-0.01773938,  1.0260629 ,  0.01182094],
       [-0.01651459,  0.01182094,  1.0043827 ]])

how to generate random integer

In [36]:
np.random.randint(0, 10, size=(3, 3))

array([[0, 6, 4],
       [4, 8, 3],
       [3, 6, 4]])

In [38]:
np.random.choice(10, size=(3, 3))

array([[7, 9, 8],
       [4, 9, 5],
       [5, 4, 7]])