<a href="https://colab.research.google.com/github/oluarolu/checkfolder/blob/master/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
L = [1, 2, 3]

In [0]:
A = np.array([1, 2, 3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [0]:
L.append(4)

In [8]:
L

[1, 2, 3, 4]

In [9]:
L + [5]

[1, 2, 3, 4, 5]

Broadcasting ---- in numpy

In [10]:
A + np.array([4])

array([5, 6, 7])

vector addition

In [11]:
A + np.array([4,5,6])

array([5, 7, 9])

Other opperations on List and array

scalar multiplication

In [12]:
2 * A

array([2, 4, 6])

list scalar multiplication is repitition

In [13]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

to add 3 to each elements in a list

use for Loop - option 1

first create a new List that is empty

In [0]:
L2 =[]
for e in L:
  L2.append(e + 3)

In [15]:
L2

[4, 5, 6, 7]

DO the same thing with list comprehension

In [16]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

Want to multiple L by L

In [0]:
L2 =[]
for e in L:
  L2.append(e**2)

In [18]:
L2

[1, 4, 9, 16]

using numpy

In [19]:
A**2

array([1, 4, 9])

In [20]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

DOT operations in numpy

In [0]:
a = np.array([1,2])
b = np.array([3,4])

In [22]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
dot

11

another approach

In [24]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [25]:
np.sum(a * b)

11

In [26]:
(a*b).sum()

11

In [27]:
np.dot(a, b)

11

In [28]:
a.dot(b)

11

In [29]:
a @ b

11

Speed Test

In [0]:
from datetime import datetime

#note: you can also use %timeit - To check that later

In [0]:
a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

create a function

In [0]:
def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a , b):
    result += e * f
  return result

In [0]:
t0 = datetime.now()
for t in range(T):
  slow_dot_product(a , b)
dt1 = datetime.now() - t0

using list comprehension

In [0]:
t0 = datetime.now()
[slow_dot_product(a, b) for t in range(T)]
dt1 = datetime.now() - t0

In [0]:
t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

In [37]:
print("dt1/dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1/dt2: 47.838132339656724


Matric

In [38]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [39]:
L[0]

[1, 2]

In [40]:
L[0][1]

2

using numpy array

In [42]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [43]:
A[0][1]

2

In [45]:
A[0,1]

2

In [46]:
A[:,0]

array([1, 3])

In [47]:
A.T

array([[1, 3],
       [2, 4]])

In [48]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [49]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [51]:
B = np.array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

Matric operations

In [52]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [53]:
np.linalg.det(A)

-2.0000000000000004

In [54]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [55]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [56]:
np.trace(A)

5

In [57]:
np.diag(A)

array([1, 4])

In [58]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [59]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [0]:
Lam, V=np.linalg.eig(A)

In [64]:
V[:, 0] * Lam[0] == A@ V[:, 0]

array([ True, False])

In [65]:
V[:, 0] * Lam[0], A @ V[:, 0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [66]:
np.allclose(V[:, 0] * Lam[0], A @ V[:, 0])

True

In [67]:
np.allclose(V @np.diag(Lam), A @V)

True